variable "project_id" {}
variable "region_name" {}
variable "vm_name" {}
variable "machine_type" {}
variable "zone" {}
variable "image" {}
variable "vpc_name" {}
variable "sub_cidr" {}
variable "sub_name" {}
variable "disk_name" {}
variable "disk_type" {}
variable "disk_size" {}